# Generated by Django 5.1.5 on 2025-02-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
    ]
